apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongo-root-username: bXhrdWJuZXRlcw== # base64-encoded username
  mongo-root-password: bWF4d2VsbDIy # base64-encoded password

# MONGODB Service
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector: 
    app: mongodb
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017