apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  labels:
    app: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      automountServiceAccountToken: false
      containers:
      - name: mongo-express
        image: mongo-express:1.0.0
        ports:
        - containerPort: 8081
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
            ephemeral-storage: "1Gi"
          limits:
            cpu: "250m"
            memory: "256Mi"
            ephemeral-storage: "2Gi"
        env:
        # - name: ME_CONFIG_MONGODB_SERVER
        #   value: mongodb-service
        - name: ME_CONFIG_MONGODB_SERVER
          # value: "27017"
          valueFrom:
            configMapKeyRef:
              name: mongo-configmap
              key: database_port
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-username
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-password