apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  # mongo-root-username: <base64-encoded-username>
  mongo-root-username: bXhrdWJuZXRlcw== # the key used to reference the username in the deployment
  # mongo-root-password: <base64-encoded-password>
  mongo-root-password: bWF4d2VsbDIy # Example base64-encoded password