# apiVersion: networking.k8s.io/v1beta1
# kind: Ingress
# metadata:
#   name: mongo-express-ingress
# spec:
#   rules:
#   - host: mongo-express.local
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: mongo-express
#             port:
#               number: 8081

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mongo-express-ingress
  # annotations:
  #   nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: mongo-express.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          serviceName: mongo-express-service
          servicePort: 8081
