apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-configmap
data:
  database_url: "mongodb-service"  # The URL of the MongoDB service
  database_port: "27017"  # The port on which MongoDB is running
  # You can add more configuration options here as needed