apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  # type: ClusterIP
  # sessionAffinity: None
  # clusterIP: None
  # loadBalancerIP: None
  # externalTrafficPolicy: Cluster
  # healthCheckNodePort: 0
  # publishNotReadyAddresses: false
  # topologyKeys:
  # - kubernetes.io/hostname
  # - "topology.kubernetes.io/zone"
  # - "topology.kubernetes.io/region"